name: Node.js Tests with MySQL

on:
  pull_request:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: "rootpassword" 
          MYSQL_DATABASE: "testdb"             
          MYSQL_USER: "root"               
          MYSQL_PASSWORD: "testpassword"     
        ports:
          - 3306:3306

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment file
        run: |
          echo "hostname=localhost" >> .env
          echo "username=root" >> .env
          echo "password=rootpassword" >> .env 
          echo "database=testdb" >> .env        
          echo "port=3306" >> .env

      - name: Install dependencies
        run: npm install

      - name: Wait for MySQL to be ready
        run: sleep 20

      - name: Run tests
        run: npm test
        continue-on-error: false 

      - name: Make zip
        run: zip -r webapp.zip . -x ".git/*"

      - name: Install gcloud for packer
        run: "packer plugins install github.com/hashicorp/googlecompute"
        
      - name: Initialize packer
        run: packer init .

      - name: Format packer
        run: packer fmt .
      
      - name: Validate packer
        run: packer validate .