name: Node.js Tests with MySQL

on:
  pull_request_target:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: "${{secrets.DB_ROOT_PASSWORD}}" 
          MYSQL_DATABASE: "${{secrets.DB_NAME}}"             
          MYSQL_USER: "${{secrets.DB_USER}}"               
          MYSQL_PASSWORD: "${{secrets.DB_PASSWORD}}"     
        ports:
          - 3306:3306

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment file
        run: |
          echo "hostname=${{secrets.DB_HOST}}" >> .env
          echo "username=${{secrets.DB_USER}}" >> .env
          echo "password=${{secrets.DB_PASSWORD}}" >> .env 
          echo "database=${{secrets.DB_NAME}}" >> .env        
          echo "port=${{secrets.DB_PORT}}" >> .env

      - name: Install dependencies
        run: npm install

      - name: Wait for MySQL to be ready
        run: sleep 20

      - name: Run tests
        run: npm test

      - name: Initialize packer
        run: packer init .

      - name: Format packer
        run: packer fmt .
      
      - name: Validate packer
        run: packer validate .