name: Node.js Tests with MySQL

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: "rootpassword"   # Different from local .env value
          MYSQL_DATABASE: "test_db"             # Test database name (different from local)
          MYSQL_USER: "test_user"               # Test user (different from local)
          MYSQL_PASSWORD: "testpassword123"     # Test user password (different from local)
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment file
        run: |
          echo "hostname=127.0.0.1" >> .env
          echo "username=test_user" >> .env       # Different than in local .env
          echo "password=testpassword123" >> .env # Different than in local .env
          echo "database=test_db" >> .env         # Different than in local .env
          echo "port=3306" >> .env

      - name: Install dependencies
        run: npm install

      - name: Wait for MySQL to be ready
        run: sleep 20

      - name: Run tests
        run: npm test
