name: Deploy Web App on EC2 (AWS) and Run Integration Tests

on:
  pull_request_target:
    types: [closed]
    branches:
      - main

jobs:
  deploy_and_test_aws:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: "${{secrets.DB_ROOT_PASSWORD}}" 
          MYSQL_DATABASE: "${{secrets.DB_NAME}}"             
          MYSQL_USER: "${{secrets.DB_USER}}"               
          MYSQL_PASSWORD: "${{secrets.DB_PASSWORD}}"     
        ports:
          - 3306:3306

    steps:
    # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment file
        run: |
          echo "hostname=${{secrets.DB_HOST}}" >> .env
          echo "username=root" >> .env
          echo "password=${{secrets.DB_ROOT_PASSWORD}}" >> .env 
          echo "database=${{secrets.DB_NAME}}" >> .env        
          echo "port=${{secrets.DB_PORT}}" >> .env

      - name: Install dependencies
        run: npm install

      - name: Wait for MySQL to be ready
        run: sleep 20

      - name: Run tests
        run: npm test
        continue-on-error: false 

      - name: Make zip
        run: zip -r webapp.zip . -x ".git/*"

    # Step 2: Set up AWS CLI
      - name: Set up AWS CLI
        run: |
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws configure set region us-east-1
        
      - name: Install gcloud for packer
        run: "packer plugins install github.com/hashicorp/googlecompute"

      # Step 3: Initialize packer
      - name: Initialize packer to create EC2 instance
        run: |
          packer init .

      # Step 4: Validate packer
      - name: Validate packer to create EC2 instance
        run: |
          packer validate .

      # Step 5: Building packer
      - name: Run Packer to create AMI for EC2 instance
        run: |
          packer build \
          -var "aws_region=${{secrets.AWS_REGION}}" \
          -var "aws_db_root_password=${{secrets.DB_ROOT_PASSWORD}}" \
          -var "aws_db_name=${{secrets.DB_NAME}}" \
          aws-custom-image.pkr.hcl

      #Now we have to switch to demo
      - name: Set up AWS CLI
        run: |
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID_DEMO }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY_DEMO }}"
          aws configure set region us-east-1

      # Step 6: Trigger ASG Instance Refresh and wait for completion
      - name: Refresh Auto Scaling Group Instances
        run: |
          ASG_NAME="${{ secrets.ASG_NAME }}"

          echo "Starting instance refresh for ASG: $ASG_NAME"
          REFRESH_ID=$(aws autoscaling start-instance-refresh \
            --auto-scaling-group-name "$ASG_NAME" \
            --query "InstanceRefreshId" \
            --output text)

          echo "Instance Refresh ID: $REFRESH_ID"

          while true; do
            STATUS=$(aws autoscaling describe-instance-refreshes \
              --auto-scaling-group-name "$ASG_NAME" \
              --instance-refresh-ids "$REFRESH_ID" \
              --query "InstanceRefreshes[0].Status" \
              --output text)

            echo "Current status: $STATUS"

            if [[ "$STATUS" == "Successful" ]]; then
              echo "Instance refresh completed successfully."
              exit 0
            elif [[ "$STATUS" == "Failed" || "$STATUS" == "Cancelled" ]]; then
              echo "Instance refresh failed or was cancelled."
              exit 1
            fi

            sleep 30
          done
